"""added image_folder_path to categories table

Revision ID: 267d0b0e3136
Revises: 9e3f163e148f
Create Date: 2023-04-30 15:37:47.267238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267d0b0e3136'
down_revision = '9e3f163e148f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_folder_path', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image_folder_path')

    # ### end Alembic commands ###
