"""changed the nullable fields

Revision ID: 377842cb01ed
Revises: 5a93bf83bfc3
Create Date: 2023-05-07 09:18:11.573554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377842cb01ed'
down_revision = '5a93bf83bfc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('descriptionUkr',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('descriptionUkr',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
