"""updated fields name

Revision ID: 38aa274f3186
Revises: 267d0b0e3136
Create Date: 2023-04-30 16:26:56.550891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38aa274f3186'
down_revision = '267d0b0e3136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the 'positionNameUkr' column to 'productNameUkr'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('positionNameUkr', new_column_name='productNameUkr')

    # Rename the 'positionNameRu' column to 'productNameTranslate'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('positionNameRu', new_column_name='productNameTranslate')

    # Rename the 'descriptionRu' column to 'descriptionTranslate'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('descriptionRu', new_column_name='descriptionTranslate')

    # Rename the 'priceInHryvnias' column to 'price'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('priceInHryvnias', new_column_name='price')

    # Rename the 'producer' column to 'brand'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('producer', new_column_name='brand')

    # Rename the 'producingCountry' column to 'brandCountry'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('producingCountry', new_column_name='brandCountry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Rename the 'productNameUkr' column to 'positionNameUkr'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('productNameUkr', new_column_name='positionNameUkr')

    # Rename the 'productNameTranslate' column to 'positionNameRu'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('productNameTranslate', new_column_name='positionNameRu')

    # Rename the 'descriptionTranslate' column to 'descriptionRu'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('descriptionTranslate', new_column_name='descriptionRu')

    # Rename the 'price' column to 'priceInHryvnias'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('price', new_column_name='priceInHryvnias')

    # Rename the 'brand' column to 'producer'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('brand', new_column_name='producer')

    # Rename the 'brandCountry' column to 'producingCountry'
    with op.batch_alter_table('products') as batch_op:
        batch_op.alter_column('brandCountry', new_column_name='producingCountry')

    # ### end Alembic commands ###
