"""updating some fields to nullable

Revision ID: 947929f9e58a
Revises: 377842cb01ed
Create Date: 2023-05-15 15:59:07.448030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '947929f9e58a'
down_revision = '377842cb01ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('productCode',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('productCode',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
