"""delete_field_from_categories_table

Revision ID: dd20027f2272
Revises: 38aa274f3186
Create Date: 2023-04-30 21:14:06.808623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd20027f2272'
down_revision = '38aa274f3186'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('image_folder_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_folder_path', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
